import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import LandingContainer from "@/src/components/landing";
import styled from "@emotion/styled";
import NavigationContainer from "@/src/components/common/navigation";

const inter = Inter({ subsets: ["latin"] });

const Layout = styled.main`
  position: relative;
  display: flex;
  width: 100%;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Youngtak Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <NavigationContainer />
        <LandingContainer />
      </Layout>
    </>
  );
}
